-- UC-05 (Theo Dõi Mốc Phát Triển Của Bé): seed bộ mốc phát triển 0-24
-- tháng tuổi, dịch từ checklist chính thức của CDC "Learn the Signs. Act
-- Early." (bản sửa đổi 2022) — https://www.cdc.gov/act-early/digital-online-checklist/
-- Nhóm theo 4 nhóm kỹ năng chuẩn của CDC (Xã hội & Cảm xúc, Ngôn ngữ & Giao
-- tiếp, Nhận thức, Vận động & Thể chất), 8 mốc tháng tuổi: 2, 4, 6, 9, 12,
-- 15, 18, 24. `expected_from_month`/`expected_to_month` lấy khoảng giữa 2
-- mốc checklist liền kề (VD mốc 4 tháng: from=2, to=4).

insert into public.development_milestones (
  age_months, category, title, expected_from_month, expected_to_month, source, version, active, sort_order
) values
  (2, 'Xã hội & Cảm xúc', 'Bình tĩnh lại khi được nói chuyện hoặc bế lên', 0, 2, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 1),
  (2, 'Xã hội & Cảm xúc', 'Nhìn vào mặt bạn', 0, 2, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 2),
  (2, 'Xã hội & Cảm xúc', 'Có vẻ vui khi thấy bạn tới gần', 0, 2, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 3),
  (2, 'Xã hội & Cảm xúc', 'Cười khi bạn nói chuyện hoặc cười với bé', 0, 2, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 4),
  (2, 'Ngôn ngữ & Giao tiếp', 'Phát ra âm thanh khác ngoài tiếng khóc', 0, 2, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 5),
  (2, 'Ngôn ngữ & Giao tiếp', 'Phản ứng với âm thanh lớn', 0, 2, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 6),
  (2, 'Nhận thức', 'Nhìn theo bạn khi bạn di chuyển', 0, 2, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 7),
  (2, 'Nhận thức', 'Nhìn 1 món đồ chơi trong vài giây', 0, 2, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 8),
  (2, 'Vận động & Thể chất', 'Ngẩng đầu lên khi nằm sấp', 0, 2, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 9),
  (2, 'Vận động & Thể chất', 'Cử động cả 2 tay và 2 chân', 0, 2, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 10),
  (2, 'Vận động & Thể chất', 'Mở bàn tay trong chốc lát', 0, 2, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 11),
  (4, 'Xã hội & Cảm xúc', 'Tự cười để thu hút sự chú ý của bạn', 2, 4, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 1),
  (4, 'Xã hội & Cảm xúc', 'Cười khúc khích khi bạn cố chọc cười bé', 2, 4, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 2),
  (4, 'Xã hội & Cảm xúc', 'Nhìn bạn, cử động hoặc phát ra âm thanh để giữ sự chú ý của bạn', 2, 4, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 3),
  (4, 'Ngôn ngữ & Giao tiếp', 'Phát ra âm "ưưư", "ààà" (bập bẹ nguyên âm)', 2, 4, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 4),
  (4, 'Ngôn ngữ & Giao tiếp', 'Đáp lại bằng âm thanh khi bạn nói chuyện với bé', 2, 4, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 5),
  (4, 'Ngôn ngữ & Giao tiếp', 'Quay đầu về phía có tiếng bạn nói', 2, 4, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 6),
  (4, 'Nhận thức', 'Mở miệng khi đói và thấy vú/bình sữa', 2, 4, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 7),
  (4, 'Nhận thức', 'Nhìn tay mình với vẻ thích thú', 2, 4, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 8),
  (4, 'Vận động & Thể chất', 'Giữ đầu vững không cần đỡ khi được bế', 2, 4, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 9),
  (4, 'Vận động & Thể chất', 'Giữ đồ chơi khi bạn đặt vào tay bé', 2, 4, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 10),
  (4, 'Vận động & Thể chất', 'Dùng tay vung về phía đồ chơi', 2, 4, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 11),
  (4, 'Vận động & Thể chất', 'Đưa tay vào miệng', 2, 4, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 12),
  (4, 'Vận động & Thể chất', 'Chống khuỷu tay/cẳng tay đẩy người lên khi nằm sấp', 2, 4, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 13),
  (6, 'Xã hội & Cảm xúc', 'Nhận ra người quen', 4, 6, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 1),
  (6, 'Xã hội & Cảm xúc', 'Thích nhìn mình trong gương', 4, 6, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 2),
  (6, 'Xã hội & Cảm xúc', 'Cười thành tiếng', 4, 6, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 3),
  (6, 'Ngôn ngữ & Giao tiếp', 'Đáp lời qua lại bằng âm thanh với bạn', 4, 6, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 4),
  (6, 'Ngôn ngữ & Giao tiếp', 'Thổi "bọt bong bóng" (le lưỡi và thổi)', 4, 6, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 5),
  (6, 'Ngôn ngữ & Giao tiếp', 'Phát ra tiếng kêu the thé', 4, 6, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 6),
  (6, 'Nhận thức', 'Cho đồ vật vào miệng để khám phá', 4, 6, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 7),
  (6, 'Nhận thức', 'Với tay lấy đồ chơi mình muốn', 4, 6, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 8),
  (6, 'Nhận thức', 'Mím môi ra hiệu không muốn ăn thêm', 4, 6, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 9),
  (6, 'Vận động & Thể chất', 'Lật từ sấp sang ngửa', 4, 6, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 10),
  (6, 'Vận động & Thể chất', 'Chống thẳng tay đẩy người lên khi nằm sấp', 4, 6, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 11),
  (6, 'Vận động & Thể chất', 'Chống tay để tự ngồi vững', 4, 6, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 12),
  (9, 'Xã hội & Cảm xúc', 'Nhút nhát, bám hoặc sợ người lạ', 6, 9, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 1),
  (9, 'Xã hội & Cảm xúc', 'Thể hiện nhiều biểu cảm khác nhau: vui, buồn, giận, ngạc nhiên', 6, 9, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 2),
  (9, 'Xã hội & Cảm xúc', 'Nhìn về phía bạn khi bạn gọi tên bé', 6, 9, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 3),
  (9, 'Xã hội & Cảm xúc', 'Phản ứng khi bạn rời đi (nhìn theo, với tay hoặc khóc)', 6, 9, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 4),
  (9, 'Xã hội & Cảm xúc', 'Cười hoặc cười to khi chơi trò ú oà', 6, 9, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 5),
  (9, 'Ngôn ngữ & Giao tiếp', 'Phát ra nhiều âm khác nhau như "ma ma ma", "ba ba ba"', 6, 9, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 6),
  (9, 'Ngôn ngữ & Giao tiếp', 'Giơ tay đòi được bế lên', 6, 9, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 7),
  (9, 'Nhận thức', 'Tìm đồ vật khi thấy nó rơi khỏi tầm nhìn (như thìa hay đồ chơi)', 6, 9, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 8),
  (9, 'Nhận thức', 'Gõ 2 đồ vật vào nhau', 6, 9, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 9),
  (9, 'Vận động & Thể chất', 'Tự ngồi dậy được một mình', 6, 9, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 10),
  (9, 'Vận động & Thể chất', 'Chuyển đồ vật từ tay này sang tay kia', 6, 9, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 11),
  (9, 'Vận động & Thể chất', 'Dùng ngón tay "cào" thức ăn về phía mình', 6, 9, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 12),
  (9, 'Vận động & Thể chất', 'Ngồi vững không cần đỡ', 6, 9, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 13),
  (12, 'Xã hội & Cảm xúc', 'Chơi các trò tương tác với bạn, như ú oà, vỗ tay', 9, 12, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 1),
  (12, 'Ngôn ngữ & Giao tiếp', 'Vẫy tay chào tạm biệt', 9, 12, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 2),
  (12, 'Ngôn ngữ & Giao tiếp', 'Gọi bố/mẹ bằng "ba/bố", "ma/mẹ" hoặc tên gọi thân mật khác', 9, 12, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 3),
  (12, 'Ngôn ngữ & Giao tiếp', 'Hiểu "không" (dừng lại hoặc khựng lại khi nghe bạn nói)', 9, 12, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 4),
  (12, 'Nhận thức', 'Cho đồ vật vào hộp/cốc, ví dụ khối gỗ vào cốc', 9, 12, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 5),
  (12, 'Nhận thức', 'Tìm đồ vật bé thấy bạn giấu, ví dụ đồ chơi dưới khăn', 9, 12, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 6),
  (12, 'Vận động & Thể chất', 'Bám vịn để đứng lên', 9, 12, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 7),
  (12, 'Vận động & Thể chất', 'Đi men theo đồ nội thất khi vịn tay', 9, 12, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 8),
  (12, 'Vận động & Thể chất', 'Uống nước từ cốc không nắp khi bạn giữ cốc', 9, 12, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 9),
  (12, 'Vận động & Thể chất', 'Nhặt vật nhỏ bằng ngón cái và ngón trỏ', 9, 12, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 10),
  (15, 'Xã hội & Cảm xúc', 'Bắt chước trẻ khác khi chơi, ví dụ lấy đồ chơi ra khỏi hộp khi thấy bạn làm vậy', 12, 15, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 1),
  (15, 'Xã hội & Cảm xúc', 'Đưa cho bạn xem 1 món đồ bé thích', 12, 15, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 2),
  (15, 'Xã hội & Cảm xúc', 'Vỗ tay khi phấn khích', 12, 15, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 3),
  (15, 'Xã hội & Cảm xúc', 'Ôm thú bông hoặc đồ chơi khác', 12, 15, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 4),
  (15, 'Xã hội & Cảm xúc', 'Thể hiện tình cảm với bạn (ôm, nựng, hôn)', 12, 15, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 5),
  (15, 'Ngôn ngữ & Giao tiếp', 'Cố nói 1-2 từ ngoài "ba/bố", "ma/mẹ", ví dụ "bà" cho bóng hoặc "gâu" cho chó', 12, 15, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 6),
  (15, 'Ngôn ngữ & Giao tiếp', 'Nhìn vào đồ vật quen thuộc khi bạn gọi tên nó', 12, 15, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 7),
  (15, 'Ngôn ngữ & Giao tiếp', 'Làm theo hướng dẫn có cả cử chỉ lẫn lời nói, ví dụ đưa đồ chơi khi bạn chìa tay và nói "đưa mẹ"', 12, 15, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 8),
  (15, 'Ngôn ngữ & Giao tiếp', 'Chỉ tay để xin đồ hoặc nhờ giúp đỡ', 12, 15, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 9),
  (15, 'Nhận thức', 'Cố dùng đồ vật đúng cách, như điện thoại, cốc, sách', 12, 15, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 10),
  (15, 'Nhận thức', 'Xếp chồng ít nhất 2 vật nhỏ, ví dụ khối gỗ', 12, 15, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 11),
  (15, 'Vận động & Thể chất', 'Tự bước vài bước', 12, 15, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 12),
  (15, 'Vận động & Thể chất', 'Dùng ngón tay tự bốc ăn', 12, 15, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 13),
  (18, 'Xã hội & Cảm xúc', 'Đi ra xa bạn nhưng vẫn ngoái nhìn để chắc bạn ở gần', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 1),
  (18, 'Xã hội & Cảm xúc', 'Chỉ tay cho bạn xem thứ gì đó thú vị', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 2),
  (18, 'Xã hội & Cảm xúc', 'Chìa tay ra để bạn rửa tay cho', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 3),
  (18, 'Xã hội & Cảm xúc', 'Xem vài trang sách cùng bạn', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 4),
  (18, 'Xã hội & Cảm xúc', 'Giúp bạn mặc đồ bằng cách xỏ tay vào ống áo hoặc giơ chân lên', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 5),
  (18, 'Ngôn ngữ & Giao tiếp', 'Cố nói từ 3 từ trở lên ngoài "ba/bố", "ma/mẹ"', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 6),
  (18, 'Ngôn ngữ & Giao tiếp', 'Làm theo hướng dẫn 1 bước mà không cần cử chỉ, ví dụ đưa đồ khi bạn nói "đưa mẹ"', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 7),
  (18, 'Nhận thức', 'Bắt chước bạn làm việc nhà, ví dụ quét nhà', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 8),
  (18, 'Nhận thức', 'Chơi đồ chơi theo cách đơn giản, ví dụ đẩy xe đồ chơi', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 9),
  (18, 'Vận động & Thể chất', 'Tự đi mà không cần vịn', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 10),
  (18, 'Vận động & Thể chất', 'Vẽ nguệch ngoạc', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 11),
  (18, 'Vận động & Thể chất', 'Uống nước từ cốc không nắp, có thể còn đổ ra ngoài', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 12),
  (18, 'Vận động & Thể chất', 'Tự bốc ăn bằng tay', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 13),
  (18, 'Vận động & Thể chất', 'Cố dùng thìa', 15, 18, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 14),
  (24, 'Xã hội & Cảm xúc', 'Nhận ra khi người khác bị đau/buồn, ví dụ dừng lại hoặc tỏ vẻ buồn khi thấy ai đó khóc', 18, 24, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 1),
  (24, 'Xã hội & Cảm xúc', 'Nhìn mặt bạn để biết cách phản ứng trong tình huống mới', 18, 24, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 2),
  (24, 'Ngôn ngữ & Giao tiếp', 'Chỉ vào hình trong sách khi bạn hỏi, ví dụ "con gấu đâu?"', 18, 24, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 3),
  (24, 'Ngôn ngữ & Giao tiếp', 'Nói được ít nhất 2 từ ghép với nhau, ví dụ "thêm sữa"', 18, 24, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 4),
  (24, 'Ngôn ngữ & Giao tiếp', 'Chỉ vào ít nhất 2 bộ phận cơ thể khi bạn yêu cầu', 18, 24, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 5),
  (24, 'Ngôn ngữ & Giao tiếp', 'Dùng nhiều cử chỉ hơn ngoài vẫy tay và chỉ tay, ví dụ hôn gió hoặc gật đầu', 18, 24, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 6),
  (24, 'Nhận thức', 'Cầm 1 vật bằng tay này trong khi tay kia thao tác, ví dụ giữ hộp và mở nắp', 18, 24, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 7),
  (24, 'Nhận thức', 'Cố xoay/bấm nút, núm vặn trên đồ chơi', 18, 24, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 8),
  (24, 'Nhận thức', 'Chơi cùng lúc với nhiều hơn 1 đồ chơi, ví dụ đặt đồ ăn đồ chơi lên đĩa đồ chơi', 18, 24, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 9),
  (24, 'Vận động & Thể chất', 'Đá bóng', 18, 24, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 10),
  (24, 'Vận động & Thể chất', 'Chạy', 18, 24, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 11),
  (24, 'Vận động & Thể chất', 'Tự leo lên/xuống vài bậc thang, có hoặc không cần hỗ trợ', 18, 24, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 12),
  (24, 'Vận động & Thể chất', 'Tự ăn bằng thìa', 18, 24, 'CDC Learn the Signs. Act Early. (2022)', 'default', true, 13)
on conflict do nothing;
